### ISSUE TITLE
Build error with angular/universal

### ISSUE THREAD

**Issue by rplotkin** [angular/preboot#44] opened 2017-10-11 13:35 UTC
**Note: for support questions, please use the Universal Slack Channcel or https://gitter.im/angular/universal** 

* **I'm submitting a ...**
- [x] bug report
- [ ] feature request

* **Which parts of preboot are affected by this issue?**
- [ ] server side
- [ ] client side
- [ ] inline
- [x] build process
- [ ] docs
- [ ] tests

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
yarn build:dynamic and yarn build:static on the angular/universal app with prebuilt added errors out

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

Add preboot to the angular/universal app and run yarn build:dynamic or yarn build:static 

* **What is the expected behavior?**

Successful build

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Browser: N/A
- Language: TS 2.5
- OS:  OS X
- Platform: NodeJS

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

```
ERROR in ./node_modules/preboot/src/browser/browser-preboot.module.ts
Module build failed: Error: Typescript emitted no output for [REDACTED]/node_modules/preboot/src/browser/browser-preboot.module.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader [REDACTED]/node_modules/ts-loader/dist/index.js:47:15)
    at Object.loader ([REDACTED]/node_modules/ts-loader/dist/index.js:29:12)
 @ ./dist/server/main.bundle.js 1:17532-17585
 @ ./server.ts

ERROR in ./node_modules/preboot/src/browser/event.replayer.ts
Module build failed: Error: Typescript emitted no output for [REDACTED]/node_modules/preboot/src/browser/event.replayer.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader ([REDACTED]/node_modules/ts-loader/dist/index.js:47:15)
    at Object.loader ([REDACTED]/node_modules/ts-loader/dist/index.js:29:12)
 @ ./dist/server/main.bundle.js 1:73717-73762
 @ ./server.ts

ERROR in ./node_modules/preboot/src/server/server-preboot.module.ts
Module build failed: Error: Typescript emitted no output for [REDACTED]/node_modules/preboot/src/server/server-preboot.module.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader ([REDACTED]/node_modules/ts-loader/dist/index.js:47:15)
    at Object.loader ([REDACTED]/node_modules/ts-loader/dist/index.js:29:12)
 @ ./dist/server/main.bundle.js 1:73512-73563
 @ ./server.ts
```

**Comment by CaerusKaru** [comment] 2017-10-21 00:02
Duplicate of #41. Please see that issue for resolution instructions

**Comment by jeffwhelpley** [comment] 2017-10-23 12:26
Yes, as mentioned above check out #41. If the Webpack change I mentioned isn't viable then let me know.

**Closed by jeffwhelpley** 2017-10-23 12:26 UTC
