### ISSUE TITLE
page turn to white screen if one of the httpclient requast have delay

### ISSUE THREAD

**Issue by hesampour** [angular/preboot#81] opened 2018-03-18 06:03 UTC
Hi
I tried to use the preboot module but the problem is that when routing if one of my http request in the page has delay the page change to blank screen suddenly.

**Comment by CaerusKaru** [comment] 2018-03-18 06:07
Duplicate of https://github.com/angular/preboot/issues/57

**Comment by CaerusKaru** [comment] 2018-03-18 06:08
You'll need to activate preboot manually if your app takes longer than expected

**Closed by CaerusKaru** 2018-03-18 06:07 UTC
