### ISSUE TITLE
Object doesn't support property or method 'from': IE11

### ISSUE THREAD

**Issue by dneeleman** [angular/preboot#63] opened 2018-01-17 10:41 UTC
**Note: for support questions, please use the Universal Slack Channcel or https://gitter.im/angular/universal** 

* **I'm submitting a ...**
- [x] bug report
- [ ] feature request

* **Which parts of preboot are affected by this issue?**
- [ ] server side
- [x] client side
- [x] inline
- [ ] build process
- [ ] docs
- [ ] tests

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
On IE11, Win 10. The following code will give a 'error: Object doesn't support property or method 'from''. It is part of the inline script.

`
// we want to add an event listener for each node and each event
for (var _i = 0, _a = Array.from(nodes); _i < _a.length; _i++) {
        var node = _a[_i];
        _loop_1(node);
    }`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
Just refresh the webpage with debugger catching the error.

* **What is the expected behavior?**
The error should not be there.

* **What is the motivation / use case for changing the behavior?**
I am debugging a problem where the whole <app> node is deleted when client tries to bootstrap, leaving the webpage a solid white screen. This happens 9/10 times after refresh, on IE10/11/Edge, but sometimes also on Safari.

* **Please tell us about your environment:**

- Browser: [IE 11 ]
- Language: [ ES5 ]
- OS:  [ Mac OS X ]
- Platform: [browser]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by CaerusKaru** [comment] 2018-01-19 02:37
It looks like there's a [Polyfill](https://github.com/mathiasbynens/Array.from) for this. Did you try it?

**Comment by dneeleman** [comment] 2018-01-19 09:12
@CaerusKaru Correct, I have tried this. Seems to not work with IE11 on Windows 10. Also tried the CoreJS/Array version as well.

**Comment by Quovadisqc** [comment] 2018-01-19 20:29
@CaerusKaru Using core-js ES6 polyfills included with @angular/cli projects in the `src/polyfills.ts` file fixes this.

It does not fix #64 though.

**Comment by Quovadisqc** [comment] 2018-01-25 15:55
@CaerusKaru I might have found a problem that makes polyfills usage harder.

The problem is that in some instances, preboot kicks in before CLI polyfills are loaded.

If you pause execution at https://github.com/angular/preboot/blob/master/src/lib/api/event.recorder.ts#L47 in chrome, CLI scripts are already loaded and everything works perfectly. In IE11, some CLI scripts have not yet been downloaded (including polyfills) which causes the `Object doesn't support property or method 'from'` exception.

There are a few ways to solve this:

**Comment by Quovadisqc** [comment] 2018-01-25 16:07
@CaerusKaru I might have found a problem that makes polyfills usage harder.

The problem is that in some instances, preboot kicks in before CLI polyfills are loaded.

If you pause execution at https://github.com/angular/preboot/blob/master/src/lib/api/event.recorder.ts#L47 in chrome, CLI scripts are already loaded and everything works perfectly. In IE11, some CLI scripts have not yet been downloaded (including polyfills) which causes the `Object doesn't support property or method 'from'` exception.

There are a few ways to solve this:

- Users could manually insert polyfills that are needed for preboot higher, in the <head> tag (CLI scripts are inserted at the end of the footer). This might not be the correct solution since it should probably work with the official CLI setup.
- You could wait for document state to be complete before initializing preboot start
```
if (doc.body && doc.readyState === 'complete') {
    start(data);
}
```
This also might be optimal since it would delay preboot initialisation.
What do you think?

On a side note, even while using all of the CLI polyfills, you also need to polyfill `element.remove`.

**Comment by CaerusKaru** [comment] 2018-01-25 19:34
@Quovadisqc Thank you for looking into this so intently. It might be worth adding an "IE compatibility" section to the README in a PR.

Here's the problem with option (2): it fundamentally nullifies what preboot is supposed to be doing. Think about it, by the time `doc.ReadyState === 'complete'`, the Angular client app has already been loaded and is starting to bootstrap. This means that preboot has missed the boat on capturing events in the meantime, and for very slow UAs, this could practically be an eternity (in browser-land).

Thus, and I don't like this solution any more than you might, I think option (1) is the only viable option at this point. It might be worth going to the CLI team and requesting a feature for polyfill placement when building an application. Just note that you can automate this yourself by capturing the SSR output and reordering the resultant HTML to place polyfills at the beginning of the HEAD instead of the end of the body.

It might be worth exploring removing the Polyfill-required aspects of the code. I know that the `remove` can just be converted to `parentNode.removeChild`, and the `Event` can just not fire if not available (though we should still convert to `CustomEvent` since it's easier to polyfill -- as you mentioned in #65). Can you add that to your PR? This particular issue can be resolved by using a standard for loop through the `NodeList` in `EventReplayer` instead of creating an iterable using `Array.from`.

I'll add the first and third workarounds to #62 so that it's incorporated in the next beta and hopefully ease these pains. Apologies for introducing them in the first place, but I guess that's why this is still beta! I'll talk to @jeffwhelpley and @vikerman about possibly adding Travis/Browserstack/Saucelabs support for this repo to ensure cross-browser compatibility in the future.

**Comment by jeffwhelpley** [comment] 2018-01-25 19:50
Thanks for the work on this @CaerusKaru. Agreed on all your points. My access to this repo has been temporarily removed while the Angular team makes some adjustments. So, @vikerman you will have to help out in merging these PRs. Just slack me if you want to talk about them or have any questions.

**Comment by Quovadisqc** [comment] 2018-01-25 21:17
@CaerusKaru
No problem, I'm glad to help!

I think you are right, replacing functions that need to be polyfilled might be the best solution. 

CLI polyfills were only needed because of Array.from which you replaced in #62. The other polyfills are not covered by core-js scope and therefore would be added manually anyways.

**Closed** 2018-02-12 23:45 UTC

**Comment by dneeleman** [comment] 2018-02-14 09:10
@CaerusKaru Array.from is still used in EventRecorder. IE will still error on this.

https://github.com/angular/preboot/blob/a10e4af9e2867098974ddf790b3fed9b2fbb9b26/src/lib/api/event.recorder.ts#L194

**Comment by CaerusKaru** [comment] 2018-02-14 16:00
Will be fixed by #73

**Comment by CaerusKaru** [comment] 2018-02-14 16:12
@dneeleman I'll cut a beta.3 release later today or early tomorrow, once @mgol's PRs are in and once #72 is fully resolved.

**Comment by dneeleman** [comment] 2018-02-14 16:13
@CaerusKaru You guys are the best, thanks for the hard work!

**Comment by dottodot** [comment] 2018-02-15 18:16
I still this error when using 6.0.0-beta.2

**Comment by CaerusKaru** [comment] 2018-02-15 18:23
@dottodot See my comment above. I'm still waiting on #72, but if I don't get an update by tonight, I'll cut the beta.3 release to resolve this.

**Comment by jfrei** [comment] 2018-07-17 17:07
I'm not sure if this helps anyone, as I had a similar but different error, but just for shits and giggles, I tried importing es7 stuff and it worked for me (mostly) after that:

import 'core-js/es7/array';
import 'core-js/es7/object';

**Comment by kajalbh99** [comment] 2019-02-01 07:19
https://github.com/w3c/respec/issues/1025#issuecomment-434030447 solved my issue.

**Comment by kenmorechalfant** [comment] 2019-03-06 21:07
> I'm not sure if this helps anyone, as I had a similar but different error, but just for shits and giggles, I tried importing es7 stuff and it worked for me (mostly) after that:
> 
> import 'core-js/es7/array';
> import 'core-js/es7/object';

Is that in addition to the es6 ones or that's not necessary?

**Comment by jimguyer** [comment] 2019-05-01 12:53
Go into polyfills.ts (in the src folder by default) and just uncomment the following imports:

/***************************************************************************************************
 * BROWSER POLYFILLS
 */

`/** IE9, IE10 and IE11 requires all of the following polyfills. **/
 import 'core-js/es6/symbol';
 import 'core-js/es6/object';
 import 'core-js/es6/function';
 import 'core-js/es6/parse-int';
 import 'core-js/es6/parse-float';
 import 'core-js/es6/number';
 import 'core-js/es6/math';
 import 'core-js/es6/string';
 import 'core-js/es6/date';
 import 'core-js/es6/array';
 import 'core-js/es6/regexp';
 import 'core-js/es6/map';
 import 'core-js/es6/set';`
Note that the comment is literally in the file, so this is easy to find.

**Comment by jimguyer** [comment] 2019-05-01 12:58
Go into polyfills.ts (in the src folder by default) and just uncomment the following imports for IE9, IE10, IE11:


![Polyfill](https://user-images.githubusercontent.com/7738710/57017921-4164ed80-6bef-11e9-83a5-7228777d7ce1.jpg)

**Comment by IAMtheIAM** [comment] 2020-05-29 01:14
@jimguyer Thanks for that tip. I completely missed that I have to uncomment those lines for IE11 support. It should probably be uncommented by default, but the Angular CLI team probably has their reasons for not doing that.
